server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    generate-ddl: true
    #    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          batch_size: 30
        order_inserts: true
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        generate_statistics: false
  sql:
    init:
      mode: never